version: '3'
services:
  worker_one:
    build: 
      context: .
    ports:
      - "3000:3000"
    container_name: worker-cluster-1
    environment:
      - RPC_ENDPOINT=ws://host.docker.internal:9988

  worker_two:
    build: 
      context: .
    ports:
      - "3001:3001"
    container_name: worker-cluster-2
    environment:
      - RPC_ENDPOINT=ws://host.docker.internal:9988

  worker_three:
    build: 
      context: .
    ports:
      - "3002:3002"
    container_name: worker-cluster-3
    environment:
      - RPC_ENDPOINT=ws://host.docker.internal:9988